function Hd = Chebyshev_bpf(interval)
%CHEBYSHEV_BPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 02-Aug-2021 12:02:54

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 16200;  % Sampling Frequency
fc1 = interval(1);
fc2 = interval(2);

Fstop1 = fc1-100;        % First Stopband Frequency
if Fstop1 <=0
    Fstop1 = 50;
end

Fpass1 =fc1;        % First Passband Frequency
Fpass2 = fc2;       % Second Passband Frequency
Fstop2 = fc2+100;       % Second Stopband Frequency
Astop1 = 60;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
