function Hd = GenEquirriple_bpf(interval)
%GENEQUIRRIPLE_BPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 02-Aug-2021 13:16:32

% Generalized REMEZ FIR Bandpass filter designed using the FIRGR function.

% All frequency values are in Hz.
Fs = 16200;  % Sampling Frequency
fc1 = interval(1);
fc2 = interval(2);

Fstop1 = fc1-100;        % First Stopband Frequency
if Fstop1 <=0
    Fstop1 = 50;
end

Fpass1 = fc1;        % First Passband Frequency
Fpass2 = fc2;       % Second Passband Frequency
Fstop2 = fc2+100;       % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the coefficients using the FIRGR function.
b  = firgr('minorder', [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 ...
           0 1 1 0 0], [Dstop1 Dpass Dstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
